/**
 * MainView Component
 * Displays the current project idea with all 10 sections
 * Implements Requirements 3.5, 4.1, 5.1, 6.1
 */

import React from 'react';
import { ProjectBriefing } from '../types';
import './MainView.css';

export interface MainViewProps {
  currentIdea: ProjectBriefing | null;
  isDailyFeatured: boolean;
  onSave: () => void;
  onDiscard: () => void;
  onGenerate: () => void;
  isLoading: boolean;
}

export const MainView: React.FC<MainViewProps> = ({
  currentIdea,
  isDailyFeatured,
  onSave,
  onDiscard,
  onGenerate,
  isLoading
}) => {
  if (isLoading) {
    return (
      <div className="main-view">
        <div className="loading-container">
          <div className="loading-spinner" role="status" aria-label="Loading" />
          <p className="loading-text">Generating your project idea...</p>
        </div>
      </div>
    );
  }

  if (!currentIdea) {
    return (
      <div className="main-view">
        <div className="empty-state">
          <h2>Welcome to DevForge</h2>
          <p>Generate your first project idea to get started</p>
          <button 
            className="button button-primary" 
            onClick={onGenerate}
          >
            Generate New Idea
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="main-view">
      {/* Daily Featured Badge */}
      {isDailyFeatured && (
        <div className="daily-featured-badge">
          <span className="badge-icon">⭐</span>
          <span className="badge-text">Daily Featured Idea</span>
        </div>
      )}

      {/* Project Briefing Card */}
      <div className="briefing-card">
        {/* Section 1: Project Title */}
        <header className="briefing-header">
          <h1 className="briefing-title">{currentIdea.title}</h1>
          <div className="briefing-meta">
            <span className="meta-item">{currentIdea.category}</span>
            <span className="meta-separator">•</span>
            <span className="meta-item">{currentIdea.difficultyLevel}</span>
            <span className="meta-separator">•</span>
            <span className="meta-item">{currentIdea.estimatedTime}</span>
          </div>
        </header>

        {/* Section 2: Project Description */}
        <section className="briefing-section">
          <h2 className="section-title">Description</h2>
          <p className="section-content">{currentIdea.description}</p>
        </section>

        {/* Section 3: Target Audience */}
        <section className="briefing-section">
          <h2 className="section-title">Target Audience</h2>
          <p className="section-content">{currentIdea.targetAudience}</p>
        </section>

        {/* Section 4: Core Features */}
        <section className="briefing-section">
          <h2 className="section-title">Core Features</h2>
          <ul className="feature-list">
            {currentIdea.coreFeatures.map((feature, index) => (
              <li key={index} className="feature-item">{feature}</li>
            ))}
          </ul>
        </section>

        {/* Section 5: Technical Requirements */}
        <section className="briefing-section">
          <h2 className="section-title">Technical Requirements</h2>
          <div className="tech-tags">
            {currentIdea.technicalRequirements.map((tech, index) => (
              <span key={index} className="tech-tag">{tech}</span>
            ))}
          </div>
        </section>

        {/* Section 8: Learning Outcomes */}
        <section className="briefing-section">
          <h2 className="section-title">Learning Outcomes</h2>
          <ul className="outcome-list">
            {currentIdea.learningOutcomes.map((outcome, index) => (
              <li key={index} className="outcome-item">{outcome}</li>
            ))}
          </ul>
        </section>

        {/* Section 9: Potential Extensions */}
        <section className="briefing-section">
          <h2 className="section-title">Potential Extensions</h2>
          <ul className="extension-list">
            {currentIdea.potentialExtensions.map((extension, index) => (
              <li key={index} className="extension-item">{extension}</li>
            ))}
          </ul>
        </section>

        {/* Section 10: Similar Projects */}
        <section className="briefing-section">
          <h2 className="section-title">Similar Projects</h2>
          <ul className="similar-list">
            {currentIdea.similarProjects.map((project, index) => (
              <li key={index} className="similar-item">{project}</li>
            ))}
          </ul>
        </section>

        {/* Generation Type Badge */}
        <div className="generation-badge">
          <span className="badge-label">Generated by:</span>
          <span className="badge-value">
            {currentIdea.generationType === 'ai' ? 'AI' : 'Algorithm'}
          </span>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="action-buttons">
        <button 
          className="button button-secondary" 
          onClick={onDiscard}
          disabled={isLoading}
        >
          Discard
        </button>
        <button 
          className="button button-primary" 
          onClick={onSave}
          disabled={isLoading}
        >
          Save Idea
        </button>
        <button 
          className="button button-accent" 
          onClick={onGenerate}
          disabled={isLoading}
        >
          Generate New Idea
        </button>
      </div>
    </div>
  );
};
