/**
 * MainView Component Tests
 * Tests rendering, user interactions, and loading states
 * Requirements: 15.1, 15.4, 15.5
 */

import { describe, test, expect, vi } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { MainView } from './MainView';
import { ProjectBriefing } from '../types';

describe('MainView Component', () => {
  const mockIdea: ProjectBriefing = {
    id: 'test-id-123',
    title: 'Test Project Title',
    description: 'This is a test project description that is long enough to meet the minimum requirements.',
    targetAudience: 'Developers learning React and TypeScript',
    coreFeatures: [
      'Feature 1',
      'Feature 2',
      'Feature 3',
      'Feature 4',
      'Feature 5'
    ],
    technicalRequirements: ['React', 'TypeScript', 'CSS'],
    difficultyLevel: 'Intermediate',
    estimatedTime: '2-3 weeks',
    learningOutcomes: [
      'Learn React hooks',
      'Master TypeScript',
      'Understand component patterns'
    ],
    potentialExtensions: [
      'Add authentication',
      'Implement real-time updates',
      'Add mobile support'
    ],
    similarProjects: [
      'Project A',
      'Project B',
      'Project C'
    ],
    category: 'Web Development',
    generatedAt: Date.now(),
    generationType: 'algorithmic'
  };

  const mockHandlers = {
    onSave: vi.fn(),
    onDiscard: vi.fn(),
    onGenerate: vi.fn()
  };

  test('renders loading state when isLoading is true', () => {
    render(
      <MainView
        currentIdea={null}
        isDailyFeatured={false}
        isLoading={true}
        {...mockHandlers}
      />
    );

    expect(screen.getByText('Generating your project idea...')).toBeInTheDocument();
    expect(screen.getByRole('status')).toBeInTheDocument();
  });

  test('renders empty state when no current idea', () => {
    render(
      <MainView
        currentIdea={null}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    expect(screen.getByText('Welcome to DevForge')).toBeInTheDocument();
    expect(screen.getByText('Generate your first project idea to get started')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /generate new idea/i })).toBeInTheDocument();
  });

  test('renders project briefing with all 10 sections', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    // Section 1: Title
    expect(screen.getByText('Test Project Title')).toBeInTheDocument();

    // Section 2: Description
    expect(screen.getByText(/This is a test project description/)).toBeInTheDocument();

    // Section 3: Target Audience
    expect(screen.getByText('Developers learning React and TypeScript')).toBeInTheDocument();

    // Section 4: Core Features
    expect(screen.getByText('Feature 1')).toBeInTheDocument();
    expect(screen.getByText('Feature 5')).toBeInTheDocument();

    // Section 5: Technical Requirements
    expect(screen.getByText('React')).toBeInTheDocument();
    expect(screen.getByText('TypeScript')).toBeInTheDocument();

    // Section 6: Difficulty Level (in meta)
    expect(screen.getByText('Intermediate')).toBeInTheDocument();

    // Section 7: Estimated Time (in meta)
    expect(screen.getByText('2-3 weeks')).toBeInTheDocument();

    // Section 8: Learning Outcomes
    expect(screen.getByText('Learn React hooks')).toBeInTheDocument();

    // Section 9: Potential Extensions
    expect(screen.getByText('Add authentication')).toBeInTheDocument();

    // Section 10: Similar Projects
    expect(screen.getByText('Project A')).toBeInTheDocument();
  });

  test('displays daily featured badge when isDailyFeatured is true', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={true}
        isLoading={false}
        {...mockHandlers}
      />
    );

    expect(screen.getByText('Daily Featured Idea')).toBeInTheDocument();
    expect(screen.getByText('⭐')).toBeInTheDocument();
  });

  test('does not display daily featured badge when isDailyFeatured is false', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    expect(screen.queryByText('Daily Featured Idea')).not.toBeInTheDocument();
  });

  test('displays generation type badge', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    expect(screen.getByText('Generated by:')).toBeInTheDocument();
    expect(screen.getByText('Algorithm')).toBeInTheDocument();
  });

  test('displays AI badge for AI-generated ideas', () => {
    const aiIdea = { ...mockIdea, generationType: 'ai' as const };
    
    render(
      <MainView
        currentIdea={aiIdea}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    expect(screen.getByText('AI')).toBeInTheDocument();
  });

  test('calls onSave when Save button is clicked', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    const saveButton = screen.getByRole('button', { name: /save idea/i });
    fireEvent.click(saveButton);

    expect(mockHandlers.onSave).toHaveBeenCalledTimes(1);
  });

  test('calls onDiscard when Discard button is clicked', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    const discardButton = screen.getByRole('button', { name: /discard/i });
    fireEvent.click(discardButton);

    expect(mockHandlers.onDiscard).toHaveBeenCalledTimes(1);
  });

  test('calls onGenerate when Generate New Idea button is clicked', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    const generateButton = screen.getByRole('button', { name: /generate new idea/i });
    fireEvent.click(generateButton);

    expect(mockHandlers.onGenerate).toHaveBeenCalledTimes(1);
  });

  test('disables buttons when isLoading is true', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={false}
        isLoading={true}
        {...mockHandlers}
      />
    );

    // Should not render buttons in loading state
    expect(screen.queryByRole('button', { name: /save idea/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /discard/i })).not.toBeInTheDocument();
    expect(screen.queryByRole('button', { name: /generate new idea/i })).not.toBeInTheDocument();
  });

  test('renders all core features', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    mockIdea.coreFeatures.forEach(feature => {
      expect(screen.getByText(feature)).toBeInTheDocument();
    });
  });

  test('renders all technical requirements as tags', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    mockIdea.technicalRequirements.forEach(tech => {
      expect(screen.getByText(tech)).toBeInTheDocument();
    });
  });

  test('renders category in metadata', () => {
    render(
      <MainView
        currentIdea={mockIdea}
        isDailyFeatured={false}
        isLoading={false}
        {...mockHandlers}
      />
    );

    expect(screen.getByText('Web Development')).toBeInTheDocument();
  });
});
